<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Fable.Browser.Dom" Version="2.20.0" />
    <PackageVersion Include="Fable.Browser.Event" Version="1.7.0" />
    <PackageVersion Include="Fable.Core" Version="5.2.0" />
    <PackageVersion Include="Fable.Package.SDK" Version="1.4.0" />
    <PackageVersion Include="Fable.Promise" Version="3.2.0" />
    <PackageVersion Include="FSharp.Core" Version="10.0.100" />
    <PackageVersion Include="FSharp.UMX" Version="1.1.0" />
  </ItemGroup>
</Project>
