<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <DefineConstants>FABLE_COMPILER</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="QUnit.fsi" />
    <Compile Include="QUnit.fs" />
    <Compile Include="QUnit.Tests.fs" />
    <Compile Include="Adaptive.Tests.fs" />
    <Compile Include="MapTests.fs" />
    <Compile Include="SetTests.fs" />
    <Compile Include="ListTests.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\Mibo.Fable\Mibo.Fable.fsproj" />
    <PackageReference Include="Fable.Core" />
  </ItemGroup>
</Project>
