<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <DefineConstants>FABLE_COMPILER</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Worker.fs" />
    <Compile Include="MvuWorker.fs" />
    <Compile Include="AdaptiveWorker.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\Mibo.Fable\Mibo.Fable.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Browser.Dom" />
    <PackageReference Include="Fable.Core" />
  </ItemGroup>
</Project>
